[package]
name = "devupload"
version = "1.1.0"
authors = ["dev-harsh1998 <dev-harsh1998@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.26.0"
ftp = "3.0.1"
rpassword = "4.0"